export const GET_ROBOTS = 'GET_ROBOTS';
export const GET_ROBOTS_SUCCESS = 'GET_ROBOTS_SUCCESS';
export const GET_ROBOTS_FAILURE = 'GET_ROBOTS_FAILURE';

export const EXTINGUISH_ROBOT = 'EXTINGUISH_ROBOT';
export const EXTINGUISH_ROBOT_SUCCESS = 'EXTINGUISH_ROBOT_SUCCESS';
export const EXTINGUISH_ROBOT_FAILURE = 'EXTINGUISH_ROBOT_FAILURE';