export const GET_ROBOTS = 'GET_ROBOTS';
export const GET_ROBOTS_SUCCESS = 'GET_ROBOTS_SUCCESS';
export const GET_ROBOTS_FAILURE = 'GET_ROBOTS_FAILURE';

export const EXTINGUISH_ROBOT = 'EXTINGUISH_ROBOT';
export const EXTINGUISH_ROBOT_SUCCESS = 'EXTINGUISH_ROBOT_SUCCESS';
export const EXTINGUISH_ROBOT_FAILURE = 'EXTINGUISH_ROBOT_FAILURE';

export const RECYCLE_ROBOTS = 'RECYCLE_ROBOTS';
export const RECYCLE_ROBOTS_SUCCESS = 'RECYCLE_ROBOTS_SUCCESS';
export const RECYCLE_ROBOTS_FAILURE = 'RECYCLE_ROBOTS_FAILURE';

export const SHIP_ROBOTS = 'SHIP_ROBOTS';
export const SHIP_ROBOTS_SUCCESS = 'SHIP_ROBOTS_SUCCESS';
export const SHIP_ROBOTS_FAILURE = 'SHIP_ROBOTS_FAILURE';
